Repository 0-complexity/G8_testing, pull requests merged in 2018-03, with the labels that each got.

#343 add disks tests
  functional_testing/Openvcloud/RESTful/framework/api/client.py
  functional_testing/Openvcloud/RESTful/framework/api/cloudapi/disks.py
  functional_testing/Openvcloud/RESTful/testcases/cloudapi/test01_accounts.py
  functional_testing/Openvcloud/RESTful/testcases/cloudapi/test01_disks.py
  functional_testing/Openvcloud/RESTful/testcases/cloudapi/test02_users.py
  functional_testing/Openvcloud/RESTful/testcases/cloudbroker/test01_accounts.py
  functional_testing/Openvcloud/RESTful/testcases/libcloud/test01_libvirt.py
  functional_testing/Openvcloud/RESTful/testcases/testcase_base.py
Labels: state_inprogress

#344 fix ovc & acl tests
  functional_testing/Openvcloud/ovc_master_hosted/ACL/a_basic_operations/acl_cloudspace_test.py
  functional_testing/Openvcloud/ovc_master_hosted/ACL/a_basic_operations/acl_level1group_test.py
  functional_testing/Openvcloud/ovc_master_hosted/ACL/a_basic_operations/acl_usergroup_test.py
  functional_testing/Openvcloud/ovc_master_hosted/OVC/a_basic/machine_tests.py
  functional_testing/Openvcloud/ovc_master_hosted/OVC/a_basic/network_tests.py
  functional_testing/Openvcloud/ovc_master_hosted/OVC/a_basic/users_tests.py
  functional_testing/Openvcloud/ovc_master_hosted/OVC/b_extended/machine_tests.py
  functional_testing/Openvcloud/ovc_master_hosted/Portal/framework/pages/admin_portal/cloud_broker/Images.py
  functional_testing/Openvcloud/ovc_master_hosted/Portal/framework/pages/admin_portal/cloud_broker/accounts.py
  functional_testing/Openvcloud/ovc_master_hosted/Portal/framework/pages/admin_portal/cloud_broker/cloudspaces.py
  functional_testing/Openvcloud/ovc_master_hosted/Portal/framework/pages/admin_portal/cloud_broker/users.py
  functional_testing/Openvcloud/ovc_master_hosted/Portal/framework/pages/admin_portal/cloud_broker/virtualmachines.py
  functional_testing/Openvcloud/ovc_master_hosted/Portal/framework/utils/utils.py
  functional_testing/Openvcloud/ovc_master_hosted/Portal/framework/xpath.py
  functional_testing/Openvcloud/ovc_master_hosted/Portal/testcases/admin_portal/cloud_broker/test05_images.py
  functional_testing/Openvcloud/ovc_master_hosted/Portal/testcases/admin_portal/general/test02_admin_menu.py
  functional_testing/Openvcloud/ovc_master_hosted/Portal/testcases/end_user/home/test03_knowlege_base.py
  functional_testing/Openvcloud/ovc_master_hosted/Portal/testcases/end_user/machines/test02_machine_creation.py
  functional_testing/Openvcloud/ovc_master_hosted/Portal/travis_portal_script.sh
  functional_testing/Openvcloud/tools/travis_script.sh
  functional_testing/Openvcloud/utils/utils.py
Labels: state_inprogress

#364 add disks acl tests
  functional_testing/Openvcloud/RESTful/framework/api/client.py
  functional_testing/Openvcloud/RESTful/framework/api/cloudapi/disks.py
  functional_testing/Openvcloud/RESTful/testcases/cloudapi/test01_disks.py
  functional_testing/Openvcloud/RESTful/testcases/testcase_base.py
Labels: state_inprogress

#367 Task 356
  functional_testing/Openvcloud/ovc_master_hosted/OVC/d_long_tests/machine_tests.py
Labels: in progress, state_inprogress

#371 Cloudapi account permissions tests
  functional_testing/Openvcloud/RESTful/framework/api/cloudapi/accounts.py
  functional_testing/Openvcloud/RESTful/testcases/cloudapi/test02_accounts.py
Labels: in progress, state_inprogress

#362 Cloudspace
  functional_testing/Openvcloud/RESTful/framework/api/client.py
  functional_testing/Openvcloud/RESTful/framework/api/cloudapi/machines.py
  functional_testing/Openvcloud/RESTful/framework/api/cloudbroker/cloudspace.py
  functional_testing/Openvcloud/RESTful/framework/api/cloudbroker/machine.py
  functional_testing/Openvcloud/RESTful/testcases/cloudbroker/test02_cloudspaces.py
Labels: state_inprogress, state_ready

#378 zerorobot framework
  functional_testing/zrobot_templates/framework/__init__.py
  functional_testing/zrobot_templates/framework/constructor.py
  functional_testing/zrobot_templates/framework/ovc_utils/__init__.py
  functional_testing/zrobot_templates/framework/ovc_utils/templates/account.yaml
  functional_testing/zrobot_templates/framework/ovc_utils/templates/actions.yaml
  functional_testing/zrobot_templates/framework/ovc_utils/templates/base.yaml
  functional_testing/zrobot_templates/framework/ovc_utils/templates/disk.yaml
  functional_testing/zrobot_templates/framework/ovc_utils/templates/node.yaml
  functional_testing/zrobot_templates/framework/ovc_utils/templates/openvcloud.yaml
  functional_testing/zrobot_templates/framework/ovc_utils/templates/sshkey.yaml
  functional_testing/zrobot_templates/framework/ovc_utils/templates/vdc.yaml
  functional_testing/zrobot_templates/framework/ovc_utils/templates/vdcuser.yaml
  functional_testing/zrobot_templates/framework/ovc_utils/utils.py
  functional_testing/zrobot_templates/framework/utils/utils.py
Labels: in progress, state_inprogress

#384 add teardown on utils
  functional_testing/zrobot_templates/framework/ovc_utils/utils.py
Labels: in progress, state_inprogress

#385 edit for cloudspace actions
  functional_testing/zrobot_templates/framework/ovc_utils/utils.py
Labels: in progress, state_inprogress

#379 refresh jwt
  functional_testing/zrobot_templates/framework/ovc_utils/__init__.py
  functional_testing/zrobot_templates/framework/ovc_utils/utils.py
Labels: in progress, state_inprogress
